### ISSUE TITLE
Error: duplicates present

### ISSUE THREAD

**Issue by pdhrati02** [Gibbons-Lab/mbtools#2]
Hi,
I am trying to use mbtools for amplicon sequence analysis. I am facing an issue in the first step which says that there are duplicated Ids. 
My samples are paired end reads labelled as: 01t2_sx_L001_R1_001.fastq , 01t2_sx_L001_R2_001.fastq, 01t4_sy_L001_R1_001.fastq, 01t4_sy_L001_R2_001.fastq, 04t2_sx_L001_R1_001.fastq, 04t2_sx_L001_R2_001.fastq   and so on.

But I end up getting warnings like:
There are duplicated ids, please fix them before advancing to other workflow steps.

 Check for duplicate key values in i each of which join to the same group in x over and over again. If that's ok, try by=.EACHI to run j for each group to avoid the large allocation. If you are sure you wish to proceed, rerun with allow.cartesian=TRUE.

Can you help me with the same?
Any help will be appreicated.

Thank you

Kind regards
DP

**Comment by cdiener** [comment]
Hi,

for the automatic detection of paired-end files, mbtools only supports Illumina format (`ID_S1_L001_R1_001.fastq`) or SRA format (`ID_1.fastq`). Yours is almost Illumina but has an invalid injection order specification (the `sx`) part. You can either rename your files or provide the correct regular expression to `find_read_files`, for instance, the following should work:

```R
library(mbtools)

pattern <- "([A-Za-z0-9\\-\\.]+)_(\\w+)_L(\\d+)_R(\\d+)_001.f"  # your file name structure
anns <- c("id", "suffix", "lane", "direction")  # what the fields mean

files <- find_read_files(".", pattern, anns)
```

**Comment by pdhrati02** [comment]
Thank you for your quick response, I think I was not clear with the file name I have but its just like the one you say:
01t1_S1_L001_R1_001.fastq ----this is my file name
Do you think that the t1/t2 is creating an issue? 

I will also try the pattern step, but wanted to make sure as to why is this not working?

Thank you
Best
DP

**Comment by cdiener** [comment]
Okay in this case you do have duplicated IDs. That can happen if a sample was run on several lanes or if you have copies of the files in subfolders (find_read_files traverses subdirectories as well). After doing `files <- find_read_files(...)` what is the output of 

```R
files[duplicated(files$id)]
```

**Comment by pdhrati02** [comment]
Hi,
When I try files <- find_read_files(...) it says:
 There are duplicated ids, please fix them before advancing to other workflow steps. Duplicated: 01T6, 02T12, 02T6

I went ahead and tried files[duplicated(files$id)] to which I got the duplicated ID table and the paths:

 id injection_order lane
1:  01T6              32    1
2: 02T12              60    1
3:  02T6              13    1
4:  01T6              32    1
5:  01T6              32    1
6: 02T12              60    1
7: 02T12              60    1
8:  02T6              13    1
9:  02T6              13    1

Now here it is considering all my reverse and forward files (which obviously have the same ID to be duplicated). 
The folder on which I used this command has the following files:
02T12_S60_L001_R2_001.fastq
02T12_S60_L001_R1_001.fastq
02T6_S13_L001_R2_001.fastq
02T6_S13_L001_R1_001.fastq
01T6_S32_L001_R2_001.fastq
01T6_S32_L001_R1_001.fastq

Thank you for your help
DP

**Comment by pdhrati02** [comment]
Hi, 
I tried files[duplicated(files$id)] and it returns the following:
Empty data.table (0 rows and 5 cols): forward,reverse,id,injection_order,lane

My present folder is an example folder and contains the following files:
02T12_S60_L001_R2_001.fastq
02T12_S60_L001_R1_001.fastq
02T6_S13_L001_R2_001.fastq
02T6_S13_L001_R1_001.fastq
01T6_S32_L001_R2_001.fastq
01T6_S32_L001_R1_001.fastq

Thank you for your help
DP

**Comment by cdiener** [comment]
Yep, check your files. You have at least 4 files with the id "02T12". One common thing that happens is that you have the files in your top directory and then run preprocessing which creates a subfolder for the cleaned files. Make sure that the raw files are in their own subfolder such as "./raw" for instance.

**Comment by pdhrati02** [comment]
I understand, thank you very much for your help. It works fine now. The issue was the subfolders itself.

Thank you once again for your help
DP

**Comment by cdiener** [comment]
Awesome, glad you found a fix!
