### ISSUE TITLE
mbtools guide

### ISSUE THREAD

**Issue by Fla1487** [Gibbons-Lab/mbtools#3]
There is a mbtools guide to use completely the package? i.e. similar to phyloseq guide?
Thanks a lot

**Comment by cdiener** [comment]
Is https://gibbons-lab.github.io/mbtools/ what you are looking for? The Articles section covers most of the package.

**Comment by Fla1487** [comment]
Thank you so much for replaying.

I am interested in using mbtools for 16s data analysis, like I have seen on a recent paper that you have published. I do not understand two main step: a) removing primers or not biologic sequences (in qiime2 2 is before DADA2 alghoritm); b) assigning taxnomy.

Thank you in advance
Flavio

Inviato da Posta<https://go.microsoft.com/fwlink/?LinkId=550986> per Windows

Da: Christian ***@***.***>
Inviato: mercoledì 13 ottobre 2021 22:44
A: ***@***.***>
Cc: De Maio ***@***.***>; ***@***.***>
Oggetto: Re: [Gibbons-Lab/mbtools] mbtools guide (#3)


Is https://gibbons-lab.github.io/mbtools/<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgibbons-lab.github.io%2Fmbtools%2F&data=04%7C01%7Cflavio.demaio%40unicatt.it%7Cd8c2a9f5b4b949b12af208d98e8a3a60%7Cb94f7d7481ff44a9b5886682acc85779%7C0%7C0%7C637697546598841766%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Y4jVM7S4GA3W8R%2F1C0fhEXFjpqwJ7iPsZdxfMG5lNXs%3D&reserved=0> what you are looking for? The Articles section covers most of the package.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGibbons-Lab%2Fmbtools%2Fissues%2F3%23issuecomment-942705780&data=04%7C01%7Cflavio.demaio%40unicatt.it%7Cd8c2a9f5b4b949b12af208d98e8a3a60%7Cb94f7d7481ff44a9b5886682acc85779%7C0%7C0%7C637697546598851760%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=pSjZMX4qjRVOR%2BqcwRb5QJ5HTtrm6u%2BeJHB9gycGZJ4%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FANDJXTHSG222WLC4BRBTJLTUGXVRLANCNFSM5F43Z67Q&data=04%7C01%7Cflavio.demaio%40unicatt.it%7Cd8c2a9f5b4b949b12af208d98e8a3a60%7Cb94f7d7481ff44a9b5886682acc85779%7C0%7C0%7C637697546598851760%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=5OVFJaGMOVTxBrxCJhMo7X%2BBeN%2FDhHsVgQVERHtpXx8%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cflavio.demaio%40unicatt.it%7Cd8c2a9f5b4b949b12af208d98e8a3a60%7Cb94f7d7481ff44a9b5886682acc85779%7C0%7C0%7C637697546598861753%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Sc5IzXThozSWV3YoqcbHX4ZkjDKHEMI8nhC1NMNahM8%3D&reserved=0> or Android<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cflavio.demaio%40unicatt.it%7Cd8c2a9f5b4b949b12af208d98e8a3a60%7Cb94f7d7481ff44a9b5886682acc85779%7C0%7C0%7C637697546598861753%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=GobMe6KxBH8KIOEk3HYHvjCACTTQ77a5yyzwVm5O7kc%3D&reserved=0>.



[http://static.unicatt.it/ext-portale/FirmaOutlook.jpg]<http://www.unicatt.it/>
[http://static.unicatt.it/ext-portale/5xmille-firma-mail-scritta.jpg]
